// Generates TypeScript types from the JSON Schemas into src/generated/.
// Run with `pnpm generate` after any schema change and commit the output.
import { compile } from 'json-schema-to-typescript'
import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const schemasDir = path.join(here, '..', 'schemas')
const outDir = path.join(here, '..', 'src', 'generated')

await mkdir(outDir, { recursive: true })

const files = (await readdir(schemasDir)).filter((f) => f.endsWith('.schema.json')).sort()
const header = '/* eslint-disable */\n// GENERATED by scripts/generate-types.mjs — do not edit.\n\n'
const index = []
const declared = new Map() // type name → module that declares it

for (const file of files) {
  const schema = stripConditionals(JSON.parse(await readFile(path.join(schemasDir, file), 'utf8')))
  const base = file.replace('.schema.json', '')
  const ts = await compile(schema, schema.title ?? base, {
    bannerComment: '',
    cwd: schemasDir,
    additionalProperties: false,
    strictIndexSignatures: true,
    declareExternallyReferenced: true,
    $refOptions: { resolve: { file: { order: 1 } } },
  })
  await writeFile(path.join(outDir, `${base}.ts`), header + dedupe(ts, base))
  index.push(`export * from './${base}.js'`)
}

await writeFile(path.join(outDir, 'index.ts'), header + index.join('\n') + '\n')

/**
 * Types referenced across schemas (e.g. BridgeErrorKind in stream-control)
 * are declared once, in the first module that emits them, and imported elsewhere.
 */
function dedupe(ts, module) {
  const lines = ts.split('\n')
  const out = []
  const imports = new Map()
  let skipping = false
  let skipKind = null
  for (const line of lines) {
    if (skipping) {
      if (
        (skipKind === 'interface' && line === '}') ||
        (skipKind === 'type' && line.trimEnd().endsWith(';'))
      )
        skipping = false
      continue
    }
    const m = line.match(/^export (type|interface) (\w+)\b/)
    if (m) {
      const [, kind, name] = m
      const owner = declared.get(name)
      if (owner && owner !== module) {
        imports.set(name, owner)
        if (kind === 'type' && line.trimEnd().endsWith(';')) continue
        if (kind === 'interface' && line.trimEnd().endsWith('}')) continue
        skipping = true
        skipKind = kind
        continue
      }
      declared.set(name, module)
    }
    out.push(line)
  }
  const importLines = Array.from(imports.entries()).map(
    ([name, owner]) => `import type { ${name} } from './${owner}.js'`,
  )
  return (importLines.length ? importLines.join('\n') + '\n\n' : '') + out.join('\n')
}

/**
 * `if`/`then` conditionals express runtime requiredness (e.g. `errors` when
 * kind is `validation`) that TypeScript cannot model; the generator would
 * otherwise widen the whole object to an index signature.
 */
function stripConditionals(node) {
  if (Array.isArray(node)) return node.map(stripConditionals)
  if (node && typeof node === 'object') {
    const out = {}
    for (const [key, value] of Object.entries(node)) {
      if (key === 'if' || key === 'then' || key === 'else') continue
      if (key === 'allOf' && Array.isArray(value)) {
        const kept = value.filter(
          (entry) => !(entry && typeof entry === 'object' && ('if' in entry || 'then' in entry)),
        )
        if (kept.length > 0) out.allOf = kept.map(stripConditionals)
        continue
      }
      out[key] = stripConditionals(value)
    }
    return out
  }
  return node
}
console.log(`generated ${files.length} type files in src/generated`)
